### ISSUE TITLE
Rich Text Issue

### ISSUE THREAD

**Issue by SamRaeburn** [TonyTewsAngels/Dev#155]
After having tested the XML Parser it is clear that the data stored in the rich text elements in the XML file is correctly stored by the program. However the font and font size are not used by the handler (even though they are stored correctly the handler uses the font size / font in the main text element)

**Comment by ajewers** [comment]
This issue is actually with the renderer's use of the supplied data. Fix in progress

**Comment by ajewers** [comment]
@SamRaeburn to re test
