### ISSUE TITLE
Audio Handler coordinates

### ISSUE THREAD

**Issue by SamRaeburn** [TonyTewsAngels/Dev#161]
X end coordinate is correct but Y end coordinate is 0

**Comment by SamRaeburn** [comment]
Note - This issue does not occur if only a play/pause button is visible, it only occurs when full controls are visble. X coordnates are always correct. @AlexanderCash

**Comment by ajewers** [comment]
@AlexanderCash Tested - works as desired.

**Comment by AlexanderCash** [comment]
Closing this badboi
