### ISSUE TITLE
Answer Box Answers should be handled using answer objects, as is done for multiple choice

### ISSUE THREAD

**Issue by ajewers** [TonyTewsAngels/Dev#166]
The regex string answer system should be removed entirely, replaced by the array list of Answer objects, as used in the multiple choice system. The 'correct' variable will be ignored, as all answers attatched to an answer box are correct answers.

Some extension will be needed to deal with numerical, range based answers.

**Comment by ajewers** [comment]
@SamRaeburn to re-test all answerbox stuff, including issues #173 #195

**Comment by SamRaeburn** [comment]
Will do tomorrow
