### ISSUE TITLE
Bug with using an audio object in the editor

### ISSUE THREAD

**Issue by SamRaeburn** [TonyTewsAngels/Dev#167]
If the audio handler is set to hide the progress bar and then it is moved the progress bar will be made visible.
A similar thing happens if you change page(i.e. create an audio object with the progress bar hidden, go to next page, return to original page and the progress bar will be visible).

**Comment by ajewers** [comment]
@SamRaeburn Audio handler initialises audio objects with controls open, their state is not maintained between slides. Could change to initialise controls closed if preferable.
