### ISSUE TITLE
Colour picker in editor

### ISSUE THREAD

**Issue by SamRaeburn** [TonyTewsAngels/Dev#170]
When using the colour picker in the editor, if 'custom colour' is selected it sometimes doesn't use or save this value regardless of what you select. Seems fairly tempremental on when it does and doesn't save/use the colour.

Another issue is that when this custom colour option is selected its modality is set such that you can not use anything else to do with the application, this causes an error when the custom colour picker appears behind the main window since you can not minimize teach easy whilst it is open...

**Comment by SamRaeburn** [comment]
The 'web' option allowing the user to enter a colour as a hex value also does not work

**Comment by ajewers** [comment]
Java FX 2.2 color picker is broken. Only works in java FX8, which is only available with java 8, which we can't use.
