### ISSUE TITLE
Rich text fragments in XML

### ISSUE THREAD

**Issue by SamRaeburn** [TonyTewsAngels/Dev#196]
Not sure if bug or just how rich text works...

When a complex rich text object is defined in an XML (a sentence with some words underlined some not etc.). If I wanted to write the following sentence:
Hello **my** name is _Sam_
It would appear in the program as:
Hello**my**name is_Sam_

(Yes I'm now pro at markdown).
Basically if a text fragment starts or ends with a space it will not display the space.

**Comment by ajewers** [comment]
@SamRaeburn to re test

**Comment by SamRaeburn** [comment]
You wish
